[package]
name = "MyRuntime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "1"
scoped-tls = "1"
async-std = "1"
futures = "0"